<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.dows.cloud</groupId>
        <artifactId>dows-aac</artifactId>
        <version>${revision}</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>aac-handler</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.dows.cloud</groupId>
            <artifactId>aac-service</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dows.cloud</groupId>
            <artifactId>aac-pojo</artifactId>
        </dependency>

        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dows.cloud</groupId>
            <artifactId>uim-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dows.cloud</groupId>
            <artifactId>rbac-api</artifactId>
        </dependency>
        <!--<dependency>
            <groupId>org.dows.cloud</groupId>
            <artifactId>aac-config</artifactId>
        </dependency>-->

        <!--        <dependency>
                    <groupId>org.dows.cloud</groupId>
                    <artifactId>aac-oauth</artifactId>
                </dependency>-->
        <!--<dependency>
            <groupId>org.dows.framework</groupId>
            <artifactId>cache-caffeine</artifactId>
        </dependency>

        <dependency>
            <artifactId>log-api</artifactId>
            <groupId>org.dows.cloud</groupId>
        </dependency>-->

    </dependencies>
</project>
