springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/doc会自动重定向到swagger-ui.html页面
    path: /doc
    packages-to-scan: org.dows.aac.api
  group-configs:
    - group: aac-center
      packagesToScan: org.dows.aac.rest

#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    enabled: true

---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
springdoc:
  api-docs:
    enabled: true

---
#验收环境
spring:
  config:
    activate:
      on-profile: uat
springdoc:
  api-docs:
    enabled: true

---
#生产环境
spring:
  config:
    activate:
      on-profile: pro
springdoc:
  api-docs:
    enabled: false