server:
  port: 18002
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32
  #  servlet:
  #    context-path: /${spring.application.name}
spring:
  main:
    allow-circular-references: true
  application:
    name: dows-aac
    appId: 1
  profiles:
    include: |
      mysql,apidoc,aac,captcha,cache
    active: dev



