server:
  port: 18002
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32
  #  servlet:
  #    context-path: /${spring.application.name}
spring:
  main:
    allow-circular-references: true
  application:
    name: dows-aac
  profiles:
    include: |
      mysql,apidoc,mybatis,app,
      aac-root,aac-caffeine,aac-jwt,aac-captcha,aac-uri,aac-menu,aac-role,rbac-caffeine,
      rbac-root,rbac-uri,rbac-menu,rbac-role
    active: dev



